### ISSUE TITLE
package not working

### ISSUE THREAD

**Issue by speedtreammanga** [alykoshin/gmail-send#10]
Hi there 👋

It doesn't seem to work for me :/
here's my code:

```
const send = require('gmail-send');

try {
    console.log('sending mail...');
    send({
        user: myEmail,
        from: myEmail,
        replyTo: myEmail,
        pass: '',
        subject: 'Hi you, it\'s Alex 👋',
        to: mySecondEmail,
        text: 'this is a random string',
    }, (err, res) => {
        console.log('Sending mail faileld, callback returned err: ', err, 'res:', res);
    })
} catch (err) {
    console.log('something went very wrong,', err);
}
```

Since `myEmail` doesn't have 2-Step Verification enabled I haven't entered a `pass`.
When I execute the code, nothing happens...

And are the emails supposed to also appear in the `Sent emails` from the Gmail panel ?

Thanks a bunch,
Alex

**Comment by alykoshin** [comment]
You can try to Allow less secure apps: If you don't use 2-Step Verification, you might need to allow less secure apps to access your account.
https://support.google.com/accounts/answer/6010255

**Comment by alykoshin** [comment]
I have email sent by the module in 'Sent Mail'

**Comment by alykoshin** [comment]
Ok. The reason is following.
First call to `send` is to create the object and set default config. Consequent calls are to send (and update the config if needed).
As if `require()` returned class and you must instantiate it by calling constructor (though without `new`).

Example 1:
```
const send = require('gmail-send`)();  // set no default config
send({ user,  pass, ... }, callback); // send using provided config
```
Example 2:
```
const send = require('gmail-send`)({ user, pass, .... }); // set default config
send({}, callback); // send using default config 
send({ to: 'somebody.else.com }, callback); // send using default config and override 'to' option
```
Example 3 (step-by-step):
```
const Send = require('gmail-send`)
const send = Send( config ); 
send(overridingConfig, callback); 
```
In your example there is only one call to `sen`d which sets defaults , but does not actually sends an email.

**Comment by speedtreammanga** [comment]
@alykoshin It worked, hell yes!
Awesome package my friend.

**Comment by alykoshin** [comment]
Glad it was useful for you.
