### ISSUE TITLE
Text formatting?

### ISSUE THREAD

**Issue by whasonyt** [alykoshin/gmail-send#33]
Hi, I'm super curious if you can only send plain-text and a few attachments, or if you can use text formatting in your email to make things **bold**, underline, _italics_. 

I've tried markdown and even going as far as HTML formatting to format the text in the email, but both just return the raw text.

Is there anyway to format the text using `gmail-send`?
Thanks,
Will 😃

**Comment by reallyfionn** [comment]
Yep, we need this, this project seems inactive though..

**Comment by whasonyt** [comment]
Update: found it but it's not documented. Instead of doing `text:`, you need to do `html:` 😄
