### ISSUE TITLE
Last email in "to" array is picked up quoted

### ISSUE THREAD

**Issue by nicholaswmin** [alykoshin/gmail-send#4]
In the following code:

```javascript
const gmailSend = require("gmail-send")({
  user: "foo@bar.com",
  pass: "foobarfoobar",
  to: [
    "foo@bar.com",
    "bar@bar.com",
    "baz@bar.com" // this is picked up quoted
  ],
  subject: "Hello world",
  text: "Hello world"
});
```

The above sends emails to these addresses:
    
   foo@bar.com // OK, receives the email,
   bar@bar.com // OK, receives the email,
   "baz@bar.com" // this is sent quoted - which causes this address not to receive the email at all.

### Screenshot from Gmail

Here's a screenshot from my Gmail "to" field showing this issue:

![Screenshot of Gmail "To" field showing the last address in quotes](https://cloud.githubusercontent.com/assets/3926463/25355019/e8de3c02-293d-11e7-9ce7-978a91d6983d.png)

**Comment by alykoshin** [comment]
Fixed and updated in NPM.
Please, confirm it is working.

**Comment by nicholaswmin** [comment]
Fixed, thanks.

**Comment by alykoshin** [comment]
You are welcome.
